---
extends: stylelint-config-gds/scss
ignoreFiles: src/govuk/vendor/**/*
rules:
  declaration-no-important: ~
  indentation: ~
  scss/comment-no-loud: ~
  scss/operator-no-unspaced: ~
  selector-pseudo-element-colon-notation: ~
  selector-type-no-unknown: ~
  value-keyword-case: ~
  value-list-max-empty-lines: ~
