---
extends: stylelint-config-gds/scss
ignoreFiles: src/govuk/vendor/**/*
rules:
  declaration-no-important: ~
  indentation: ~
  selector-pseudo-element-colon-notation: ~
  value-list-max-empty-lines: ~
