---
extends: stylelint-config-gds/scss
ignoreFiles: src/govuk/vendor/**/*
rules:
  declaration-no-important: ~
  indentation: ~
  media-feature-parentheses-space-inside: ~
  no-duplicate-selectors: ~
  no-eol-whitespace: ~
  no-extra-semicolons: ~
  rule-empty-line-before: ~
  scss/comment-no-loud: ~
  scss/operator-no-unspaced: ~
  selector-pseudo-element-colon-notation: ~
  selector-type-no-unknown: ~
  value-keyword-case: ~
  value-list-max-empty-lines: ~
